"""FROZEN template — copy this to experiments/<exp_name>/strategy.py.

Do not edit this file. Edit your copy under experiments/<your_exp_name>/.

The contract:
  - Module-scope: docstring (with `# alpha-meta` block), imports, the four
    REQUIRED constants (REBAL/TOP_N/WEIGHT_SCHEME/LOOKBACK_DAYS), helper
    function defs, and one `signal(ctx) -> DataFrame` function.
  - signal() returns DataFrame[date × ticker] of scores. Higher = more bullish.
    NaN excludes that ticker on that date. Pipeline picks top TOP_N per
    rebal date by descending score.
  - PIT-safe: NEVER use future bars. Negative `.shift(-N)` is hard-rejected
    at AST. `pd.read_*` and `open()` are forbidden — data only via ctx.
  - WEIGHT_SCHEME = "equal" only (long-only, 1/TOP_N each). Other schemes
    not yet wired.
"""
from __future__ import annotations

import pandas as pd

from alpha_lab.core import TrialContext


# alpha-meta
# lever:        <free-form: factor family or invention — "12-1 momentum", "low-vol", ...>
# base:         <parent exp_name, or 'template' if from scratch>
# hypothesis:   <one sentence — which axis, which direction, why>


# Required contract constants (numbers / allowed strings only)
REBAL = "M"              # "M" | "W" | "Q"
TOP_N = 30               # int in [5, 200]
WEIGHT_SCHEME = "equal"  # only "equal" wired
LOOKBACK_DAYS = 252      # int — informational; signal computes its own


def signal(ctx: TrialContext) -> pd.DataFrame:
    """Return DataFrame[date × ticker] of scores. Higher = more bullish.

    NaN values exclude that ticker on that date. The pipeline picks the
    top-TOP_N tickers per rebal date by descending score and equal-weights.

    PIT safety: only positive shifts (look at the past). At backtest time T
    the alpha model uses the most recent signal row strictly < T.
    """
    px = ctx.adj_close                          # date × ticker
    return px.pct_change(LOOKBACK_DAYS).shift(21)  # 12-1 momentum baseline
